package vista;

import controlador.Categoria_Controller;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Categoria;

public class FrmInternoCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInternoCategoria
     */
    public FrmInternoCategoria() {
        initComponents();
        this.setSize(new Dimension(450, 300));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcionCategoria = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nueva Categoría");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(txtDescripcionCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 280, 30));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        /*Categoria categoria = new Categoria();
        Categoria_Controller controladorCategoria = new Categoria_Controller();

        //validar campos vacios
        if (txtDescripcionCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo descripción");
        } else {

            if (!controladorCategoria.existeCategoria(txtDescripcionCategoria.getText().trim())) {
                categoria.setDescripcion(txtDescripcionCategoria.getText().trim());
                categoria.setEstado(1);

                if (controladorCategoria.guardar(categoria)) {
                    JOptionPane.showMessageDialog(null, "Se registraron los datos correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "!Error al guardar los datos!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "La categoria ya existe, registra una categoria diferente");
            }

        }
        //Limpiar campos
        txtDescripcionCategoria.setText("");*/

        Categoria categoria = new Categoria();
        Categoria_Controller controladorCategoria = new Categoria_Controller();

// Validar campos vacíos
        if (txtDescripcionCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo descripción");
        } else {
            // Validar y asignar descripción
            if (!txtDescripcionCategoria.getText().matches("^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ\\s]+$")) {
                JOptionPane.showMessageDialog(null, "El campo Descripción solo puede contener letras, números y espacios");
                txtDescripcionCategoria.setBackground(Color.red);
                return;
            }
            categoria.setDescripcion(txtDescripcionCategoria.getText().trim());
            categoria.setEstado(1);

            if (!controladorCategoria.existeCategoria(txtDescripcionCategoria.getText().trim())) {
                if (controladorCategoria.guardar(categoria)) {
                    JOptionPane.showMessageDialog(null, "Se registraron los datos correctamente");
                    txtDescripcionCategoria.setBackground(Color.green); // Pintar de verde el campo de descripción
                } else {
                    JOptionPane.showMessageDialog(null, "!Error al guardar los datos!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "La categoría ya existe, registra una categoría diferente");
            }
        }

// Limpiar campos
        txtDescripcionCategoria.setText("");

    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDescripcionCategoria;
    // End of variables declaration//GEN-END:variables
}
