package vista;

import controlador.Usuario_Controller;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Usuario;

public class FrmInternoUsuario extends javax.swing.JInternalFrame {

    public FrmInternoUsuario() {
        initComponents();
        this.setSize(new Dimension(450, 450));
        this.setTitle("Registrar Nuevo Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        comboRol = new javax.swing.JComboBox<>();
        txtGuardar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teléfono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rol:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombres:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, -1));
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 160, -1));

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dni:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, -1));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, -1));

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Rol:", "administrador", "vendedor" }));
        getContentPane().add(comboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 160, -1));

        txtGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar.png"))); // NOI18N
        txtGuardar.setText("Guardar");
        txtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(txtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 130, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarActionPerformed
        /*Usuario usuario = new Usuario();
        Usuario_Controller controladorUsuario = new Usuario_Controller();
        String rol = "";
        rol = comboRol.getSelectedItem().toString().trim();

        //Validar campos
        if (txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtContraseña.getText().isEmpty() || txtUsuario.getText().isEmpty() || txtContraseña.getText().isEmpty() || txtTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
            txtNombres.setBackground(Color.red);
            txtApellidos.setBackground(Color.red);
            txtUsuario.setBackground(Color.red);
            txtContraseña.setBackground(Color.red);
            txtTelefono.setBackground(Color.red);
            comboRol.setBackground(Color.red);
        } else {
            if (!controladorUsuario.existeUsuario(txtDni.getText().trim())) {
                if (rol.equalsIgnoreCase("Seleccione Rol:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione Rol:");
                } else {
                    try {
                        usuario.setNombre(txtNombres.getText().trim());
                        usuario.setApellido(txtApellidos.getText().trim());
                        usuario.setDni(txtDni.getText().trim());
                        usuario.setUsuario(txtUsuario.getText().trim());
                        usuario.setContraseña(txtContraseña.getText().trim());
                        usuario.setTelefono(txtTelefono.getText().trim());
                        usuario.setEstado(1);

                        if (rol.equalsIgnoreCase("Administrador")) {
                            usuario.setRol("Administrador");
                        } else if (rol.equalsIgnoreCase("Vendedor")) {
                            usuario.setRol("Vendedor");
                        }

                        usuario.setEstado(1);

                        if (controladorUsuario.guardar(usuario)) {
                            JOptionPane.showMessageDialog(null, "Se registraron los datos correctamente");
                            txtNombres.setBackground(Color.green);
                            txtApellidos.setBackground(Color.green);
                            txtDni.setBackground(Color.green);
                            txtUsuario.setBackground(Color.green);
                            txtContraseña.setBackground(Color.green);
                            txtTelefono.setBackground(Color.green);
                            this.comboRol.setSelectedItem("Seleccione Rol:");
                            Limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "!Error al guardar los datos!");
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error en " + e);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Ya existe el usuario, por favor ingresa un usuario diferente");
            }
        }*/

        Usuario usuario = new Usuario();
        Usuario_Controller controladorUsuario = new Usuario_Controller();
        String rol = comboRol.getSelectedItem().toString().trim();
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String dni = txtDni.getText().trim();
        String usuarioText = txtUsuario.getText().trim();
        String contraseña = txtContraseña.getText().trim();
        String telefono = txtTelefono.getText().trim();

        // Validar campos
        if (nombres.isEmpty() || apellidos.isEmpty() || contraseña.isEmpty() || usuarioText.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
            ColorRojoRegistroFallido();
        } else {
            if (!nombres.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
                JOptionPane.showMessageDialog(null, "El nombre solo puede contener letras y espacios");
                txtNombres.setBackground(Color.red);
                return;
            }
            if (!apellidos.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
                JOptionPane.showMessageDialog(null, "El apellido solo puede contener letras y espacios");
                txtApellidos.setBackground(Color.red);
                return;
            }
            if (!dni.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "El DNI solo puede contener números");
                txtDni.setBackground(Color.red);
                return;
            }
            if (!telefono.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "El teléfono solo puede contener números");
                txtTelefono.setBackground(Color.red);
                return;
            }
            //ColorRojoRegistroFallido();

            if (!controladorUsuario.existeUsuario(dni)) {
                if (rol.equalsIgnoreCase("Seleccione Rol:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione Rol:");
                } else {
                    try {
                        usuario.setNombre(nombres);
                        usuario.setApellido(apellidos);
                        usuario.setDni(dni);
                        usuario.setUsuario(usuarioText);
                        usuario.setContraseña(contraseña);
                        usuario.setTelefono(telefono);
                        usuario.setEstado(1);

                        if (rol.equalsIgnoreCase("Administrador")) {
                            usuario.setRol("Administrador");
                        } else if (rol.equalsIgnoreCase("Vendedor")) {
                            usuario.setRol("Vendedor");
                        }

                        if (controladorUsuario.guardar(usuario)) {
                            JOptionPane.showMessageDialog(null, "Se registraron los datos correctamente");
                            ColorVerdeRegistroExitoso();
                            Limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "!Error al guardar los datos!");
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error en " + e);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe el usuario, por favor ingresa un usuario diferente");
            }
        }
    }//GEN-LAST:event_txtGuardarActionPerformed

    private void ColorRojoRegistroFallido() {
        txtNombres.setBackground(Color.red);
        txtApellidos.setBackground(Color.red);
        txtDni.setBackground(Color.red);
        txtUsuario.setBackground(Color.red);
        txtContraseña.setBackground(Color.red);
        txtTelefono.setBackground(Color.red);
        comboRol.setBackground(Color.red);
    }

    private void ColorVerdeRegistroExitoso() {
        txtNombres.setBackground(Color.green);
        txtApellidos.setBackground(Color.green);
        txtDni.setBackground(Color.green);
        txtUsuario.setBackground(Color.green);
        txtContraseña.setBackground(Color.green);
        txtTelefono.setBackground(Color.green);
        comboRol.setBackground(Color.green);
    }
    
    private void Limpiar() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtDni.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtTelefono.setText("");
    }

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDni;
    private javax.swing.JButton txtGuardar;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables


}
