package vista;

import Vista.FrmInternoCobrar;
import Vista.InterGestionVentas;
import controlador.Config_Usuario_Controller;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class FrmMenuPrincipal extends javax.swing.JFrame {

    public static JDesktopPane JDesktopPane_menu;//declarar el JDesktopPane

    private String rolUsuario;
    private String nombreUsuario;
    Usuario usuario = new Usuario();

    public FrmMenuPrincipal(Usuario usuario) {
        initComponents();

        Config_Usuario_Controller control_config_usuarios = new Config_Usuario_Controller();
        rolUsuario = control_config_usuarios.obtenerRol(usuario);
        nombreUsuario = control_config_usuarios.obtenerNombreApellidoUsuario(usuario);

        if ("Administrador".equals(rolUsuario)) {
            usuarioLogueado.setText(nombreUsuario);
        } else {
            usuarioLogueado.setText(nombreUsuario);

            menuUsuarios.setEnabled(false);
            btnGestionarVenta.setEnabled(false);
        }

        this.setSize(new Dimension(1200, 700));//interfaz con esas dimensiones
        this.setExtendedState(this.MAXIMIZED_BOTH);//interfaz con pantalla completa maximizada
        this.setLocationRelativeTo(null);//interfaz centrada
        this.setTitle("Menu Principal - Sistema de Ventas");

        this.setLayout(null);

        JDesktopPane_menu = new JDesktopPane();//instanciando el JDesktopPane
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.JDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(JDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        usuarioLogueado = new javax.swing.JMenu();
        menuUsuarios1 = new javax.swing.JMenu();
        btnAbrirCaja = new javax.swing.JMenuItem();
        btnCerrarCaja = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        btnNuevoUsuario = new javax.swing.JMenuItem();
        btnGestionarUsuario = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenu();
        btnNuevaCategoria = new javax.swing.JMenuItem();
        btnGestionarCategoria = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        btnNuevoProducto = new javax.swing.JMenuItem();
        btnGestionarProducto = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        btnNuevoCliente = new javax.swing.JMenuItem();
        btnGestionarCliente = new javax.swing.JMenuItem();
        menuFacturacion = new javax.swing.JMenu();
        btnNuevaVenta = new javax.swing.JMenuItem();
        btnGestionarVenta = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioLogueado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        usuarioLogueado.setText("NOMBRE");
        usuarioLogueado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usuarioLogueado.setPreferredSize(new java.awt.Dimension(280, 50));
        jMenuBar1.add(usuarioLogueado);

        menuUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja_registradora2.png"))); // NOI18N
        menuUsuarios1.setText("Mi Caja");
        menuUsuarios1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuUsuarios1.setPreferredSize(new java.awt.Dimension(150, 50));

        btnAbrirCaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAbrirCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrir.png"))); // NOI18N
        btnAbrirCaja.setText("Abrir caja");
        btnAbrirCaja.setPreferredSize(new java.awt.Dimension(200, 30));
        btnAbrirCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCajaActionPerformed(evt);
            }
        });
        menuUsuarios1.add(btnAbrirCaja);

        btnCerrarCaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrarCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrado.png"))); // NOI18N
        btnCerrarCaja.setText("Nuevo Usuario");
        btnCerrarCaja.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCajaActionPerformed(evt);
            }
        });
        menuUsuarios1.add(btnCerrarCaja);

        jMenuBar1.add(menuUsuarios1);

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trabajo-en-equipo.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuUsuarios.setPreferredSize(new java.awt.Dimension(150, 50));

        btnNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-cliente.png"))); // NOI18N
        btnNuevoUsuario.setText("Nuevo Usuario");
        btnNuevoUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(btnNuevoUsuario);

        btnGestionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        btnGestionarUsuario.setText("Gestionar Usuarios");
        btnGestionarUsuario.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(btnGestionarUsuario);

        jMenuBar1.add(menuUsuarios);

        menuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aplicacion.png"))); // NOI18N
        menuCategorias.setText("Categorias");
        menuCategorias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuCategorias.setPreferredSize(new java.awt.Dimension(150, 50));

        btnNuevaCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevaCategoria.setText("Nueva Categoria");
        btnNuevaCategoria.setPreferredSize(new java.awt.Dimension(200, 30));
        btnNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCategoriaActionPerformed(evt);
            }
        });
        menuCategorias.add(btnNuevaCategoria);

        btnGestionarCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aplicacion.png"))); // NOI18N
        btnGestionarCategoria.setText("Gestionar Categorias");
        btnGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCategoriaActionPerformed(evt);
            }
        });
        menuCategorias.add(btnGestionarCategoria);

        jMenuBar1.add(menuCategorias);

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos-lacteos.png"))); // NOI18N
        menuProductos.setText("Producto");
        menuProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuProductos.setPreferredSize(new java.awt.Dimension(150, 50));

        btnNuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-producto.png"))); // NOI18N
        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        menuProductos.add(btnNuevoProducto);

        btnGestionarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos-lacteos.png"))); // NOI18N
        btnGestionarProducto.setText("Gestionar Productos");
        btnGestionarProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProductoActionPerformed(evt);
            }
        });
        menuProductos.add(btnGestionarProducto);

        jMenuBar1.add(menuProductos);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clasificacion.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuClientes.setPreferredSize(new java.awt.Dimension(150, 50));

        btnNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-cliente.png"))); // NOI18N
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.setPreferredSize(new java.awt.Dimension(200, 30));
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        menuClientes.add(btnNuevoCliente);

        btnGestionarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        btnGestionarCliente.setText("Gestionar Clientes");
        btnGestionarCliente.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(btnGestionarCliente);

        jMenuBar1.add(menuClientes);

        menuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bienes.png"))); // NOI18N
        menuFacturacion.setText("Ventas");
        menuFacturacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuFacturacion.setPreferredSize(new java.awt.Dimension(150, 50));

        btnNuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnNuevaVenta.setText("Registrar Ventas");
        btnNuevaVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });
        menuFacturacion.add(btnNuevaVenta);

        btnGestionarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGestionarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuraciones.png"))); // NOI18N
        btnGestionarVenta.setText("Gestionar Ventas");
        btnGestionarVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        btnGestionarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarVentaActionPerformed(evt);
            }
        });
        menuFacturacion.add(btnGestionarVenta);
        menuFacturacion.add(jSeparator1);

        jMenuBar1.add(menuFacturacion);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuSalir.setPreferredSize(new java.awt.Dimension(150, 50));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setPreferredSize(new java.awt.Dimension(150, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menuSalir.add(btnSalir);

        jMenuBar1.add(menuSalir);
        menuSalir.getAccessibleContext().setAccessibleName("btnSalir");

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        FrmInternoCobrar cobrarVentas = new FrmInternoCobrar();
        JDesktopPane_menu.add(cobrarVentas);
        cobrarVentas.setVisible(true);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClienteActionPerformed
        FrmInternoGestionarCliente frmInternoCliente = new FrmInternoGestionarCliente();
        JDesktopPane_menu.add(frmInternoCliente);
        frmInternoCliente.setVisible(true);
    }//GEN-LAST:event_btnGestionarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        FrmInternoCliente frmInternoCliente = new FrmInternoCliente();
        JDesktopPane_menu.add(frmInternoCliente);
        frmInternoCliente.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnGestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProductoActionPerformed
        FrmInternoGestionarProducto frmInternoProducto = new FrmInternoGestionarProducto();
        JDesktopPane_menu.add(frmInternoProducto);
        frmInternoProducto.setVisible(true);
    }//GEN-LAST:event_btnGestionarProductoActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        FrmInternoProducto frmNuevoProducto = new FrmInternoProducto();
        JDesktopPane_menu.add(frmNuevoProducto);
        frmNuevoProducto.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCategoriaActionPerformed
        FrmInternoGestionarCategoria frmInternoCategoria = new FrmInternoGestionarCategoria();
        JDesktopPane_menu.add(frmInternoCategoria);
        frmInternoCategoria.setVisible(true);
    }//GEN-LAST:event_btnGestionarCategoriaActionPerformed

    private void btnNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCategoriaActionPerformed
        FrmInternoCategoria frmNuevaCategoria = new FrmInternoCategoria();
        JDesktopPane_menu.add(frmNuevaCategoria);
        frmNuevaCategoria.setVisible(true);
    }//GEN-LAST:event_btnNuevaCategoriaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Deseas cerrar la sesión?", "Confirmar cierre de sesión", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {

            FrmLogin ventanaInicioSesion = new FrmLogin();
            ventanaInicioSesion.setVisible(true);

            // Cierra la ventana actual (FrmMenuPrincipal)
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarVentaActionPerformed
        InterGestionVentas gestionVentas = new InterGestionVentas();
        JDesktopPane_menu.add(gestionVentas);
        gestionVentas.setVisible(true);
    }//GEN-LAST:event_btnGestionarVentaActionPerformed

    private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
        FrmInternoGestionarUsuario frmInternoUsuario = new FrmInternoGestionarUsuario();
        JDesktopPane_menu.add(frmInternoUsuario);
        frmInternoUsuario.setVisible(true);
    }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        FrmInternoUsuario frmInternoUsuario = new FrmInternoUsuario();
        JDesktopPane_menu.add(frmInternoUsuario);
        frmInternoUsuario.setVisible(true);
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnAbrirCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCajaActionPerformed
        FrmInternoAbrirCaja frmInternoAbrirCaja = new FrmInternoAbrirCaja(usuario);
        JDesktopPane_menu.add(frmInternoAbrirCaja);
        frmInternoAbrirCaja.setVisible(true);
    }//GEN-LAST:event_btnAbrirCajaActionPerformed

    private void btnCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCajaActionPerformed
        FrmInternoCerrarCaja frmInternoCerrarCaja = new FrmInternoCerrarCaja();
        JDesktopPane_menu.add(frmInternoCerrarCaja);
        frmInternoCerrarCaja.setVisible(true);
    }//GEN-LAST:event_btnCerrarCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Usuario usuario = new Usuario();
                    new FrmMenuPrincipal(usuario).setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbrirCaja;
    private javax.swing.JMenuItem btnCerrarCaja;
    private javax.swing.JMenuItem btnGestionarCategoria;
    private javax.swing.JMenuItem btnGestionarCliente;
    private javax.swing.JMenuItem btnGestionarProducto;
    private javax.swing.JMenuItem btnGestionarUsuario;
    private javax.swing.JMenuItem btnGestionarVenta;
    private javax.swing.JMenuItem btnNuevaCategoria;
    private javax.swing.JMenuItem btnNuevaVenta;
    private javax.swing.JMenuItem btnNuevoCliente;
    private javax.swing.JMenuItem btnNuevoProducto;
    private javax.swing.JMenuItem btnNuevoUsuario;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuCategorias;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuFacturacion;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu menuUsuarios1;
    private javax.swing.JMenu usuarioLogueado;
    // End of variables declaration//GEN-END:variables
}
